In [99]:
import sqlite3
from selenium import webdriver
from selenium.webdriver.remote.webelement import WebElement
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.common.by import By
from selenium.webdriver.support import expected_conditions as EC
from bs4 import BeautifulSoup
import requests
import pandas as pd
import csv
import time

In [100]:
db_news = sqlite3.connect('C:/Develops/newspapers/중앙일보/reset.db')
c = db_news.cursor()

In [101]:
df = pd.read_excel('C:/Develops/newspapers/중앙일보/20_score_dic.xlsx', header=None)
df

,0,1,2,3,4,5,6,7,8,9,...,18,19,20,21,22,23,24,25,26,27
0,-0.95,홍익표,여영국,윤소하,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,-0.90,한정애,이정미,추혜선,김종훈,심상정,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,-0.85,이재정,김종대,정춘숙,권미혁,남인순,홍의락,이훈,김경협,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,-0.80,유승희,임재훈,김영호,강훈식,손혜원,송기헌,위성곤,김민기,제윤경,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,-0.70,이후삼,기동민,김현권,김정호,박정,정은혜,조승래,이철희,박영선,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,-0.65,김상회,서삼석,유은혜,정재호,신경민,이용득,전재수,설훈,임종성,...,이종걸,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,-0.60,금태섭,소병훈,홍영표,강창일,박주민,이학영,윤일규,황희,윤준호,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,-0.55,오영훈,변재일,윤후덕,전혜숙,우상호,김현미,김병기,전현희,송옥주,...,어기구,안호영,민홍철,윤관석,권칠승,김병욱,노웅래,김영진,유동수,NaN
8,-0.50,최재성,윤호중,김태년,박범계,이원욱,진선미,이상민,안규백,고용진,...,이개호,박광온,이상헌,오제세,정세균,최인호,김부겸,김경진,조응천,강병원
9,-0.45,박주선,추미애,김한정,이석현,진영,김정우,송영길,김철민,박병석,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,-0.40,정동영,안민석,김해영,문희상,최경환,김종회,백재현,최도자,정인화,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,-0.35,박지원,천정배,원혜영,주승용,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,-0.30,전해철,조배숙,서청원,신용현,장병완,박순자,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,-0.25,이혜훈,윤영일,황주홍,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,-0.20,정점식,김성태,최운열,함진규,원유철,장제원,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,-0.15,홍문표,강길부,이명수,손금주,김성식,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,-0.10,문진국,이용호,김영우,염동열,주광덕,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,0.00,김성원,윤상현,권은회,홍철호,김재경,정운천,김중로,김한표,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,0.05,이채익,김상훈,임이자,김세연,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,0.10,유민봉,김학용,박인숙,이철규,여상규,정양석,최교일,강석호,이언주,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,0.15,박덕흠,이은재,박맹우,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,0.20,유의동,정용기,김정재,이양수,유승민,경대수,이만희,김규환,김현아,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,0.25,하태경,정유섭,김선동,신보라,김무성,신상진,김성찬,이진복,이윤석,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,0.30,김도읍,안상수,이학재,송희경,김재원,김종석,유기준,이은권,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,0.35,장석춘,김진태,강석진,이종배,성일종,김명연,이주영,정병국,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,0.40,김기선,송언석,정태옥,이태규,김승회,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,0.45,정종섭,홍일표,심재철,김순례,이헌승,조경태,정갑윤,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,0.50,이장우,유재중,이종구,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,0.60,정우택,이종명,윤상직,백승주,김광림,김태흠,윤종필,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,0.70,이현재,권성동,김용태,추경호,강효상,박완수,최연혜,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
30,0.80,박대출,박명재,주호영,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
31,0.90,조원진,전희경,곽상도,윤한홍,곽대훈,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
32,1.00,홍문종,박성중,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [102]:
df = df.set_index(0)
df

,1,2,3,4,5,6,7,8,9,10,...,18,19,20,21,22,23,24,25,26,27
0,,,,,,,,,,,,,,,,,,,,,
-0.95,홍익표,여영국,윤소하,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
-0.90,한정애,이정미,추혜선,김종훈,심상정,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
-0.85,이재정,김종대,정춘숙,권미혁,남인순,홍의락,이훈,김경협,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
-0.80,유승희,임재훈,김영호,강훈식,손혜원,송기헌,위성곤,김민기,제윤경,김성환,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
-0.70,이후삼,기동민,김현권,김정호,박정,정은혜,조승래,이철희,박영선,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
-0.65,김상회,서삼석,유은혜,정재호,신경민,이용득,전재수,설훈,임종성,신동근,...,이종걸,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
-0.60,금태섭,소병훈,홍영표,강창일,박주민,이학영,윤일규,황희,윤준호,심기준,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
-0.55,오영훈,변재일,윤후덕,전혜숙,우상호,김현미,김병기,전현희,송옥주,민병두,...,어기구,안호영,민홍철,윤관석,권칠승,김병욱,노웅래,김영진,유동수,NaN
-0.50,최재성,윤호중,김태년,박범계,이원욱,진선미,이상민,안규백,고용진,서영교,...,이개호,박광온,이상헌,오제세,정세균,최인호,김부겸,김경진,조응천,강병원
-0.45,박주선,추미애,김한정,이석현,진영,김정우,송영길,김철민,박병석,조정식,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
-0.40,정동영,안민석,김해영,문희상,최경환,김종회,백재현,최도자,정인화,이동섭,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
-0.35,박지원,천정배,원혜영,주승용,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
-0.30,전해철,조배숙,서청원,신용현,장병완,박순자,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
-0.25,이혜훈,윤영일,황주홍,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
-0.20,정점식,김성태,최운열,함진규,원유철,장제원,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
-0.15,홍문표,강길부,이명수,손금주,김성식,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
-0.10,문진국,이용호,김영우,염동열,주광덕,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
0.00,김성원,윤상현,권은회,홍철호,김재경,정운천,김중로,김한표,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
0.05,이채익,김상훈,임이자,김세연,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
0.10,유민봉,김학용,박인숙,이철규,여상규,정양석,최교일,강석호,이언주,유성엽,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
0.15,박덕흠,이은재,박맹우,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
0.20,유의동,정용기,김정재,이양수,유승민,경대수,이만희,김규환,김현아,김성태(초선),...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
0.25,하태경,정유섭,김선동,신보라,김무성,신상진,김성찬,이진복,이윤석,한선교,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
0.30,김도읍,안상수,이학재,송희경,김재원,김종석,유기준,이은권,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
0.35,장석춘,김진태,강석진,이종배,성일종,김명연,이주영,정병국,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
0.40,김기선,송언석,정태옥,이태규,김승회,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
0.45,정종섭,홍일표,심재철,김순례,이헌승,조경태,정갑윤,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
0.50,이장우,유재중,이종구,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
0.60,정우택,이종명,윤상직,백승주,김광림,김태흠,윤종필,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
0.70,이현재,권성동,김용태,추경호,강효상,박완수,최연혜,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
0.80,박대출,박명재,주호영,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
0.90,조원진,전희경,곽상도,윤한홍,곽대훈,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1.00,홍문종,박성중,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [103]:
print(df.T.to_dict('list'))

{-0.95: ['홍익표', '여영국', '윤소하', nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan], -0.9: ['한정애', '이정미', '추혜선', '김종훈', '심상정', nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan], -0.85: ['이재정', '김종대', '정춘숙', '권미혁', '남인순', '홍의락', '이훈', '김경협', nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan], -0.8: ['유승희', '임재훈', '김영호', '강훈식', '손혜원', '송기헌', '위성곤', '김민기', '제윤경', '김성환', '박주현', '이인영', '송갑석', nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan], -0.7: ['이후삼', '기동민', '김현권', '김정호', '박정', '정은혜', '조승래', '이철희', '박영선', nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan], -0.65: ['김상회', '서삼석', '유은혜', '정재호', '신경민', '이용득', '전재수', '설훈', '임종성', '신동근', '박홍근', '박경미', '도종환', '서형수', '박선숙', '이해찬', '김두관', '이종걸', nan, nan, nan, nan, nan, nan, nan, nan, nan], -0.6: ['금태섭', '소병훈', '홍영표', '강창일', '박주민', '이학영', '윤일규', '황희', '윤준호', '심기준', '박재호', '백혜련', '이규희', '인재근', '우원식', nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan], -0.55: ['오영훈', '변재일', '윤후덕', '전혜숙', '우상호', '김현미', '김병기', '전현희', '송옥주', '민병두', '김영주', '표창원', '김광수', '김종민', '맹성규', '박용진', '신창현', '어기구', '안호영', '민홍철', '윤관석', '권칠승', '김병욱', '노웅래', '김영진', '유동수', nan], -0.5: ['최재성', '윤호중', '김태년', '박범계', '이원욱', '진선미', '이상민', '안규백', '고용진', '서영교', '박찬대', '김병관', '박완주', '김영춘', '심재권', '장정숙', '이춘석', '이개호', '박광온', '이상헌', '오제세', '정세균', '최인호', '김부겸', '김경진', '조응천', '강병원'], -0.45: ['박주선', '추미애', '김한정', '이석현', '진영', '김정우', '송영길', '김철민', '박병석', '조정식', '김수민', '이용주', '이찬열', '정성호', '김관영', nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan], -0.4: ['정동영', '안민석', '김해영', '문희상', '최경환', '김종회', '백재현', '최도자', '정인화', '이동섭', '김진표', '김동철', nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan], -0.35: ['박지원', '천정배', '원혜영', '주승용', nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan], -0.3: ['전해철', '조배숙', '서청원', '신용현', '장병완', '박순자', nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan], -0.25: ['이혜훈', '윤영일', '황주홍', nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan], -0.2: ['정점식', '김성태', '최운열', '함진규', '원유철', '장제원', nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan], -0.15: ['홍문표', '강길부', '이명수', '손금주', '김성식', nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan], -0.1: ['문진국', '이용호', '김영우', '염동열', '주광덕', nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan], 0.0: ['김성원', '윤상현', '권은회', '홍철호', '김재경', '정운천', '김중로', '김한표', nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan], 0.05: ['이채익', '김상훈', '임이자', '김세연', nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan], 0.1: ['유민봉', '김학용', '박인숙', '이철규', '여상규', '정양석', '최교일', '강석호', '이언주', '유성엽', '송석준', '민경욱', '이상돈', '정진석', nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan], 0.15: ['박덕흠', '이은재', '박맹우', nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan], 0.2: ['유의동', '정용기', '김정재', '이양수', '유승민', '경대수', '이만희', '김규환', '김현아', '김성태(초선)', nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan], 0.25: ['하태경', '정유섭', '김선동', '신보라', '김무성', '신상진', '김성찬', '이진복', '이윤석', '한선교', '나경원', nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan], 0.3: ['김도읍', '안상수', '이학재', '송희경', '김재원', '김종석', '유기준', '이은권', nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan], 0.35: ['장석춘', '김진태', '강석진', '이종배', '성일종', '김명연', '이주영', '정병국', nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan], 0.4: ['김기선', '송언석', '정태옥', '이태규', '김승회', nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan], 0.45: ['정종섭', '홍일표', '심재철', '김순례', '이헌승', '조경태', '정갑윤', nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan], 0.5: ['이장우', '유재중', '이종구', nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan], 0.6: ['정우택', '이종명', '윤상직', '백승주', '김광림', '김태흠', '윤종필', nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan], 0.7: ['이현재', '권성동', '김용태', '추경호', '강효상', '박완수', '최연혜', nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan], 0.8: ['박대출', '박명재', '주호영', nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan], 0.9: ['조원진', '전희경', '곽상도', '윤한홍', '곽대훈', nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan], 1.0: ['홍문종', '박성중', nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan]}

In [104]:
score = {-0.95: ['홍익표','여영국','윤소하'], 
         -0.9: ['한정애', '이정미', '추혜선', '김종훈', '심상정'], 
         -0.85: ['이재정', '김종대', '정춘숙', '권미혁', '남인순', '홍의락', '이훈', '김경협'], 
         -0.8: ['유승희', '임재훈', '김영호', '강훈식', '손혜원', '송기헌', '위성곤', '김민기', '제윤경', '김성환', '박주현', '이인영', '송갑석'], 
         -0.7: ['이후삼', '기동민', '김현권', '김정호', '박정', '정은혜', '조승래', '이철희', '박영선'], 
         -0.65: ['김상회', '서삼석', '유은혜', '정재호', '신경민', '이용득', '전재수', '설훈', '임종성', '신동근', '박홍근', '박경미', '도종환', '서형수', '박선숙', '이해찬', '김두관', '이종걸'], 
         -0.6: ['금태섭', '소병훈', '홍영표', '강창일', '박주민', '이학영', '윤일규', '황희', '윤준호', '심기준', '박재호', '백혜련', '이규희', '인재근', '우원식'],
         -0.55: ['오영훈', '변재일', '윤후덕', '전혜숙', '우상호', '김현미', '김병기', '전현희', '송옥주', '민병두', '김영주', '표창원', '김광수', '김종민', '맹성규', '박용진', '신창현', '어기구', '안호영', '민홍철', '윤관석', '권칠승', '김병욱', '노웅래', '김영진', '유동수'], 
         -0.5: ['최재성', '윤호중', '김태년', '박범계', '이원욱', '진선미', '이상민', '안규백', '고용진', '서영교', '박찬대', '김병관', '박완주', '김영춘', '심재권', '장정숙', '이춘석', '이개호', '박광온', '이상헌', '오제세', '정세균', '최인호', '김부겸', '김경진', '조응천', '강병원'], 
         -0.45: ['박주선', '추미애', '김한정', '이석현', '진영', '김정우', '송영길', '김철민', '박병석', '조정식', '김수민', '이용주', '이찬열', '정성호', '김관영'], 
         -0.4: ['정동영', '안민석', '김해영', '문희상', '최경환', '김종회', '백재현', '최도자', '정인화', '이동섭', '김진표', '김동철'], 
         -0.35: ['박지원', '천정배', '원혜영', '주승용'], 
         -0.3: ['전해철', '조배숙', '서청원', '신용현', '장병완', '박순자'], 
         -0.25: ['이혜훈', '윤영일', '황주홍'], 
         -0.2: ['정점식', '김성태', '최운열', '함진규', '원유철', '장제원'], 
         -0.15: ['홍문표', '강길부', '이명수', '손금주', '김성식'], 
         -0.1: ['문진국', '이용호', '김영우', '염동열', '주광덕'], 
         0.0: ['김성원', '윤상현', '권은회', '홍철호', '김재경', '정운천', '김중로', '김한표'], 
         0.05: ['이채익', '김상훈', '임이자', '김세연'], 
         0.1: ['유민봉', '김학용', '박인숙', '이철규', '여상규', '정양석', '최교일', '강석호', '이언주', '유성엽', '송석준', '민경욱', '이상돈', '정진석'], 
         0.15: ['박덕흠', '이은재', '박맹우'], 
         0.2: ['유의동', '정용기', '김정재', '이양수', '유승민', '경대수', '이만희', '김규환', '김현아', '김성태(초선)'], 
         0.25: ['하태경', '정유섭', '김선동', '신보라', '김무성', '신상진', '김성찬', '이진복', '이윤석', '한선교', '나경원'], 
         0.3: ['김도읍', '안상수', '이학재', '송희경', '김재원', '김종석', '유기준', '이은권'], 
         0.35: ['장석춘', '김진태', '강석진', '이종배', '성일종', '김명연', '이주영', '정병국'], 
         0.4: ['김기선', '송언석', '정태옥', '이태규', '김승회'], 
         0.45: ['정종섭', '홍일표', '심재철', '김순례', '이헌승', '조경태', '정갑윤'], 
         0.5: ['이장우', '유재중', '이종구'], 
         0.6: ['정우택', '이종명', '윤상직', '백승주', '김광림', '김태흠', '윤종필'], 
         0.7: ['이현재', '권성동', '김용태', '추경호', '강효상', '박완수', '최연혜'], 
         0.8: ['박대출', '박명재', '주호영'], 
         0.9: ['조원진', '전희경', '곽상도', '윤한홍', '곽대훈'], 
         1.0: ['홍문종', '박성중']
        }

In [105]:
a = []
total_cnt = 0
for key, value in score.items():
    total_cnt = 0
    for i in value:
        cnt = c.execute("SELECT count(*) FROM newspapers WHERE topkeyword LIKE '%"+i+"%' ").fetchone()
        number = int(cnt[0])
        total_cnt += number
    a.append(total_cnt)
a

[18,
 11,
 10,
 18,
 256,
 74,
 104,
 106,
 331,
 136,
 13,
 3,
 12,
 0,
 10,
 3,
 3,
 3,
 3,
 40,
 0,
 28,
 35,
 9,
 13,
 21,
 8,
 0,
 8,
 13,
 70,
 16,
 2]

In [117]:
b = []
total_cnt = 0
for key, value in score.items():
    total_cnt = 0
    head = len(value)
    for i in value:
        cnt = c.execute("SELECT count(*) FROM newspapers WHERE topkeyword LIKE '%"+i+"%' ").fetchone()
        number = int(cnt[0])
        total_cnt += number
    average = total_cnt / head
    b.append(average)
b
print(b)

[6.0, 2.2, 1.25, 1.3846153846153846, 28.444444444444443, 4.111111111111111, 6.933333333333334, 4.076923076923077, 12.25925925925926, 9.066666666666666, 1.0833333333333333, 0.75, 2.0, 0.0, 1.6666666666666667, 0.6, 0.6, 0.375, 0.75, 2.857142857142857, 0.0, 2.8, 3.1818181818181817, 1.125, 1.625, 4.2, 1.1428571428571428, 0.0, 1.1428571428571428, 1.8571428571428572, 23.333333333333332, 3.2, 1.0]

In [107]:
rest = []
negative = []
for key, value in score.items():
    total_cnt = 0
    total_cnt_nega = 0
    total_rest = 0
    
    for i in value:
        cnt = c.execute("SELECT count(*) FROM newspapers WHERE topkeyword LIKE '%"+i+"%' ").fetchone()
        number = int(cnt[0])
        total_cnt += number
        
        cnt_nega = c.execute("SELECT COUNT(*) FROM (SELECT * FROM newspapers WHERE topkeyword LIKE '%"+i+"%' intersect SELECT * FROM newspapers WHERE judge LIKE '-1')").fetchone()
        number_nega = int(cnt_nega[0])
        total_cnt_nega += number_nega
        
    total_rest = total_cnt - total_cnt_nega
    
    rest.append(total_rest)
    negative.append(total_cnt_nega)
rest
negative

[5,
 0,
 2,
 5,
 112,
 17,
 25,
 15,
 105,
 35,
 6,
 1,
 5,
 0,
 5,
 1,
 0,
 1,
 0,
 9,
 0,
 8,
 11,
 3,
 7,
 8,
 1,
 0,
 1,
 2,
 22,
 8,
 0]

In [108]:
keys = []
for key, value in score.items():
    keys.append(key)
print(keys)

[-0.95, -0.9, -0.85, -0.8, -0.7, -0.65, -0.6, -0.55, -0.5, -0.45, -0.4, -0.35, -0.3, -0.25, -0.2, -0.15, -0.1, 0.0, 0.05, 0.1, 0.15, 0.2, 0.25, 0.3, 0.35, 0.4, 0.45, 0.5, 0.6, 0.7, 0.8, 0.9, 1.0]

In [109]:
print(a)

[18, 11, 10, 18, 256, 74, 104, 106, 331, 136, 13, 3, 12, 0, 10, 3, 3, 3, 3, 40, 0, 28, 35, 9, 13, 21, 8, 0, 8, 13, 70, 16, 2]

In [110]:
print(rest)

[13, 11, 8, 13, 144, 57, 79, 91, 226, 101, 7, 2, 7, 0, 5, 2, 3, 2, 3, 31, 0, 20, 24, 6, 6, 13, 7, 0, 7, 11, 48, 8, 2]

In [111]:
print(negative)

[5, 0, 2, 5, 112, 17, 25, 15, 105, 35, 6, 1, 5, 0, 5, 1, 0, 1, 0, 9, 0, 8, 11, 3, 7, 8, 1, 0, 1, 2, 22, 8, 0]

In [112]:
cnt = c.execute("SELECT count(*) FROM newspapers WHERE topkeyword LIKE '%사랑%' ").fetchone()
number = int(cnt[0])
print(number)

43

In [113]:
cnt_nega = c.execute("SELECT COUNT(*) FROM (SELECT * FROM newspapers WHERE topkeyword LIKE '%추미애%' intersect SELECT * FROM newspapers WHERE judge LIKE '%-1%')").fetchone()
number_nega = int(cnt_nega[0])
print(number_nega)

13

In [114]:
query = c.execute("SELECT * FROM newspapers WHERE keyword LIKE '%추미애%' ")
cols = [column[0] for column in query.description]
text_result = pd.DataFrame.from_records(data=query.fetchall(), columns=cols)
text_result

,id,identical,date,press,name,title,c1,c2,c3,a1,...,place,institute,keyword,topkeyword,body,url,tf,total_body,judge,judge_ko
0,32,1100901.2021043,20210430,중앙일보,정유진.김수민(jung.yoojin@joongang.co.kr),"김오수 총장땐 본인사건 셀프수사할 판 박범계 ""심사숙고""",사회>사건_사고,정치>청와대,정치>국회_정당,None,...,"청산,봉하마을,수원지검,울산시","형사3부,중앙일보,검찰,청구,연합뉴스TV,국정원,서울중앙지검,사법연수원,정부,청와대...","김오수,총장,본인,사건,셀프,수사,박범계,심사숙고,박범계,검찰,총장,제청,조국,특별...","법무부,박범계,김오수,윤석열,국정원,사법연수원,봉하마을,김학의,노무현,서울중앙지검,조남관",'조국 특별수사팀 구성 제안'과 '김학의 전 차관 불법 출국금지' 의혹으로 검찰 수...,https://news.joins.com/article/olink/23642606,None,검찰총장 후보에 김오수·구본선·배성범·조남관. 연합뉴스 '조국 특별수...,0,부정
1,167,1100901.2021043,20210430,중앙일보,하준호.김수민(ha.junho1@joongang.co.kr),"피고인은 정상근무, 무혐의도 직무배제 법무부 내로남불",사회>미디어,사회>사건_사고,사회>노동_복지,범죄>범죄일반>폭행,...,수원지검,"서울남부지검,인권감독관실,검찰,청구,스타모빌리티,서울중앙지검,금융위원회,안산지청,대...","피고인,정상근무,무혐의,직무배제,법무부,남불,김학의,법무부,차관,불법,출국,출금,사...","법무부,본부장,출입국,외국인,수원지검,공무원,직무배제,2명,실시간,위원회,취재진,7...",김학의 전 법무부 차관 불법 출국금지(출금) 사건에 연루돼 재판에 넘겨진 차규근 법...,https://news.joins.com/article/olink/23642075,None,김학의 전 법무부 차관 불법 출국금지(출금) 사건에 연루돼 재판에 넘겨진 차규근 법...,0,중립
2,182,1100901.2021043,20210430,중앙일보,한영혜(han.younghye@joongang.co.kr),"김진욱 17억원 조은석 62억원 신고 ‘퇴임’ 박영선 58억원, 김현종 63억원",경제>부동산,None,None,None,...,"서초동,서울,강남구,노원구,서대문구,여의도,월계동,서초구,평택,경기도,안성,영등포구...","공수처장,고위공직자범죄수사처,카카오,보궐선거,정부공직자윤리위원회,현대,감사원,중소벤...","김진욱,조은석,62억,신고,퇴임,박영선,김현종,정부공직자윤리위원회,임용,퇴직,현직,...","서울,배우자,공직자,김진욱,조은석,2억,공수처,62억,김현종,박영선,도쿄,청와대,고...",정부공직자윤리위원회는 지난 1월 임용됐거나 퇴직한 전 현직 고위공직자 83명의 재산...,https://news.joins.com/article/olink/23642059,None,사진 크게보기 김진욱 고위공직자범죄수사처장. 연합뉴스 정부공직자윤리위...,0,중립
3,185,1100901.2021043,20210430,중앙일보,신용호(novae@joongang.co.kr),[신용호의 시시각각] 대통령의 공감능력은 어느 정도인가,정치>청와대,정치>국회_정당,None,None,...,"서해,광화문,프랭클린,진주만,아프리카,한국,적도,러시아","정부,민주당,일본,국회,대국,보좌관회의,국무회의,노변정담,모더나","대통령,공감능력,정도,대통령,백신,메시지,국민,불안,사과,설명,국민,어려움,위로,위...","루스벨트,노변정담,코로나,서해,국무회의,모범국가,보좌관,친밀감","""현재의 위기를 있는 그대로 말함으로써 국민이 올바른 판단을 할 수 있게 했다. 국...",https://news.joins.com/article/olink/23642055,None,문재인 대통령이 26일 청와대에서 열린 수석·보좌관 회의에서 모두 발언을 하고 있다...,0,중립
4,197,1100901.2021043,20210430,중앙일보,김수민(kim.sumin2@joongang.co.kr),"이성윤 검찰총장 후보 탈락, 추천위원 “정치 편향자”",사회>사건_사고,정치>선거,정치>청와대,None,...,"전북,울산시,수원지검,영광,창원,전남,인천,남원,경남","추천위,대검찰청,검찰,청구,법무연수원,수사심의위,검찰개혁,중앙지검,서울중앙지검,추천...","이성윤,검찰,총장,후보,탈락,편향자,추천,위원,정치,선정,김오수,구본선,배성범,조남...","지검장,법무부,조남관,이성윤,검찰총장,청와대,추천위원,김오수,추천위,중앙지검장,후보...",가장 유력한 차기 검찰총장 후보로 꼽혔던 이성윤(59 사법연수원 23기) 서울중앙지...,https://news.joins.com/article/olink/23642040,None,가장 유력한 차기 검찰총장 후보로 꼽혔던 이성윤(59·사법연수원 23기) 서울중앙지...,0,중립
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,7313,1100901.20210403,20210403,중앙일보,오현석(oh.hyunseok1@joongang.co.kr),與 불리할땐 해명창구 '김어준 뉴스공장' TBS에 연 300억,정치>선거,정치>국회_정당,None,None,...,"내곡동,서울시,서울특별시","국민의당,민주당,TBS,인턴,더불어민주당,페이스북,교통방송,선대위,뉴스공장,뉴스공장...","불리,해명창구,김어준,뉴스공장,TBS,300억,국민,기획,인터뷰,거부,바람,한쪽,정...","민주당,김어준,뉴스공장,tbs,내곡동,오세훈,300억,출연금,서울시장,첫날",“국민의힘 측에서 기획 인터뷰를 대부분 거부하시는 바람에 한쪽 정당의 후보나 관계자...,https://news.joins.com/article/olink/23621621,None,박영선(왼쪽) 더불어민주당 서울시장 후보와 방송인 김어준 씨. 사진 SNS 캡처 ...,-1,부정
96,7383,1100901.20210402,20210402,중앙일보,하준호.정유진.김민중(ha.junho1@joongang.co.kr),[단독]관용차로 이성윤 모신 김진욱 운전자는 5급 비서관,정치>청와대,정치>국회_정당,None,None,...,"울산,김,수원지검,울주군","형사3부,공수처장,공무원임용시험령 일반직,민주당,고위공직자범죄수사처,중앙일보,수원지...","관용차,이성윤,김진욱,운전자,비서관,장관,동문,한양대,법대,아버지,연수원,동기,민주...","비서관,공수처,지검장,변호사,공무원,울산,관용차,5급,수원지검,별정직,이성윤,한양대...",김진욱 고위공직자범죄수사처(공수처)장의 이성윤 서울중앙지검장 ‘황제 조사’ 논란이 ...,https://news.joins.com/article/olink/23621432,None,김진욱 고위공직자범죄수사처(공수처)장의 이성윤 서울중앙지검장 ‘황제 조사’ 논란이 ...,0,중립
97,7386,1100901.20210402,20210402,중앙일보,한영혜(han.younghye@joongang.co.kr),"선글라스 끼고 나타난 우상호 ""생태탕, 밥맛 떨어져 안먹어""",정치>국회_정당,정치>선거,정치>청와대,None,...,"내곡동,광진을,서울,저도,서울시,종로","내곡동,TBS라디오,민주당,TBS,보궐선거,검찰,더불어민주당,뉴스공장,상임선대위원장...","선글라스,우상호,생태탕,밥맛,더불어민주당,4,보궐선거,국민,사전,투표,첫날,네거티브...","생태탕,내곡동,위원장,서울,오세훈,페라가모,더불어민주당,민주당,생중계,생태탕집,유튜...",더불어민주당은 4 7 재 보궐선거 사전투표 첫날 국민의힘을 향해 네거티브 총공세를 ...,https://news.joins.com/article/olink/23621411,None,사진 크게보기 ‘지금 투표 중입니다’ 생중계에 출연 중인 이낙연 더불어민주당 상임선...,-1,부정
98,7690,1100901.20210401,20210401,중앙일보,손국희(9key@joongang.co.kr),“투표 연령 낮추자”→“20대 경험치 낮다” 與의 독한 변심,정치>선거,정치>청와대,정치>국회_정당,범죄>성범죄>성추행,...,"중앙선거여론조사심의위,서울,코엑스,삼성동","시대정신연구소장,민주당,중앙일보,알앤써치,뉴시스-리얼미터,방송3사,인천국제공항공사,...","투표,연령,경험,변심,후보,경험치,20대,20대,박영선,후보,투표,공개,서울,삼성동...","20대,지지율,여론조사,문재인,서울,양씨,친문,양준우,정치권,오세훈",“저는 어떤 후보 말대로 경험치 없는 20대입니다. 20대가 왜 박영선 후보에게 투...,https://news.joins.com/article/olink/23620585,None,“저는 어떤 후보 말대로 경험치 없는 20대입니다. 20대가 왜 박영선 후보에게 투...,-1,부정
99,7822,1100901.20210401,20210401,중앙일보,배재성(hongdoya@joongang.co.kr),유승민 “술 담배 끊고 대선 준비 윤석열도 함께 경쟁을”,정치>선거,정치>국회_정당,None,None,...,"3지대,대한민국","YTN라디오,공동선대위원장,민주당,더불어민주당,국민의힘","유승민,담배,유승민,대선,준비,윤석열,경쟁,유승민,국민,공동선대위원장,1일,출마,내...","위원장,윤석열,유승민,황보선,민주당,문재인,양극화,희망사항,진행자,법무장관,陟功黜罪...","유승민 국민의힘 공동선대위원장은 1일, 내년 3월 대통령 선거 출마가 자신의 정치인...",https://news.joins.com/article/olink/23620205,None,유승민 국민의힘 서울시장 후보 선거대책위원장이 1일 오전 서울 여의도 중앙당사에서 ...,0,중립

In [115]:
c.execute("SELECT * FROM newspapers WHERE topkeyword LIKE '%추미애%' intersect SELECT * FROM newspapers WHERE name LIKE '%고석현%'")

In [116]:
SELECT COUNT(*) FROM (SELECT * FROM newspapers WHERE topkeyword LIKE '%추미애%' intersect SELECT * FROM newspapers WHERE name LIKE '%고석현%')

SyntaxError: invalid syntax (<ipython-input-116-17b99f172e62>, line 1)

In [ ]:
c.execute("SELECT count(*) FROM newspapers WHERE topkeyword LIKE '"+value+"%' ")

In [ ]:
cnt = c.execute("SELECT count(*) FROM newspapers WHERE topkeyword LIKE '%추미애%' ").fetchone()
number = int(cnt[0])number

In [ ]:
df = df.set_index('score')
df

In [ ]:
df_set = df['name']
df_set

In [ ]:
df_set.to_dict()

In [ ]:
df.to_dict()

In [ ]:
df.T.to_dict('list')

In [ ]:
dic_1 = {0.85:['a','b'], 0.75:['c','d']}

In [ ]:
dic_1

In [ ]:
for sat in dic_1:
    for key, value in sat.items():
        print(value)

In [ ]:
a = []
for key, value in dic_1.items():
    for i in value:
        a.append(i)

In [ ]:
a